### ISSUE TITLE
Project has both npm and yarn lock files - remove whichever is unused

### ISSUE THREAD

**Issue by robbieaverill** [chec/commercejs-vuejs-boilerplate#1]
The readme says "npm install" so perhaps remove the yarn lock file.

**Comment by robbieaverill** [comment]
@kvisca thoughts?

**Comment by kvisca** [comment]
> @kvisca thoughts?

I've updated the readme to better illustrate that you can use yarn.

**Comment by robbieaverill** [comment]
Having both lock files means it's prone to having one of them becoming outdated. It's not a bit deal though, thanks for updating the readme.
